src/myproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import home_page, about_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home_name'),
    path('about/', about_page, name='about_name'),

    path('users/', include('users.urls', namespace='users')),



]


if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_page, name='register_name'),
    path('login/', auth_views.LoginView.as_view(
        template_name='users/login.html'), name='login_name'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'),
         name='logout_name'),

]

src/users/models.py
from django.db import models

# Create your models here.

src/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

src/myproj/views.py
from django.shortcuts import render


def home_page(request):
    return render(request, 'index.html')


def about_page(request):
    return render(request, 'about.html')

src/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import RegistrationForm

# Create your views here.


def register_page(request):

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = request.POST['username']
            password = request.POST['password1']
            user = authenticate(request, username=username, password=password)
            login(request, user)
            return redirect("home_name")
    else:
        form = RegistrationForm()

    context = {'form': form}

    return render(request, 'users/register.html', context)

src/templates/about.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h3 class="my-5">Welcome to About Page</h3>

{% endblock %}

src/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  {% block title %}{% endblock %}
  {% include 'base/css.html' %}
</head>

<body>
  {% include 'base/navbar.html' %}
  <div class="container">
    {% block content %}{% endblock %}
  </div>
  {% include 'base/js.html' %}
</body>

</html>

src/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
  integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'css/main.css' %}">

src/templates/base/js.html
<!-- Optional JavaScript -->
<!-- Popper.js first, then Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
  integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous">
</script>

src/templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MyProject</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home_name' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about_name' %}">About</a>
        </li>
        {% if user.is_authenticated %}
        <li class=" nav-item">
          <a class="nav-link" href="{% url 'users:logout_name' %}">Logout</a>
        </li>
        {% else %}
        <li class=" nav-item">
          <a class="nav-link" href="{% url 'users:register_name' %}">Signup</a>
        </li>
        <li class=" nav-item">
          <a class="nav-link" href="{% url 'users:login_name' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

src/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h3 class="my-5">Welcome to Home Page</h3>
<img src="{% static 'images/w5.png' %}" alt="" width="400px">

{% endblock %}

src/users/templates/users/login.html
{% extends 'base.html' %}
{% block title %}Login Page{% endblock %}

{% block content %}
<div class="card mb-4 mt-4">
  <div class="card-header">Login To Your Account
  </div>
  <div class="card-body">
    <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
  </div>
</div>
{% endblock %}

src/users/templates/users/logout.html
{% extends 'base.html' %}

{% block content %}
<h4>You have successfully logged out. <a href="{% url 'users:login_name' %}">Log back in here</a></h4>
{% endblock %}

src/users/templates/users/register.html
{% extends 'base.html' %}
{% block title %}Register Page{% endblock %}

{% block content %}
<div class="card mb-4 mt-4">
  <div class="card-header">Create An Account
  </div>
  <div class="card-body">
    <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class="btn btn-primary">Create Account</button>
    </form>
  </div>
</div>

{% endblock %}